baseURL = "https://perspectivetheory.com/"
title = "Perspective Theory | The Mental Health Website."
languageCode = "en-us"
theme = "perspective_theory_theme"

enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-132863786-6"
