baseURL = "https://masturbateless.com/"
title = "Masturbate Less | The Mental Health Website."
languageCode = "en-us"
theme = "masturbate_less_theme"

enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-132863786-7"
